### ISSUE TITLE
Should this package be named ClimateMachineParameters.jl?

### ISSUE THREAD

**Issue by glwagner** [CliMA/CLIMAParameters.jl#17]

**Comment by tapios** [comment]
Too long... CLIMAParameters.jl is clear enough.

**Comment by claresinger** [comment]
@glwagner These parameters will also be used by the other packages CliMA is developing (e.g. MoistThermodynamics.jl), so I think CLIMAParameters.jl is more clear actually.

**Comment by charleskawczynski** [comment]
Going to close this for now. Arguably, the name should be `CliMAParameters`, but I think that might cause more confusion than it's worth.
