### ISSUE TITLE
Are tuples better than vectors?

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CLIMAParameters.jl#175]
Would it make sense to return Tuples rather than Vectors in case when we have more than one parameter?

Right now I added a conversion when I am creating the parameter structs in CloudMicrophysics.jl

`parameters = map(p -> p isa Vector ? Tuple(p) : p, parameters)`

See this PR: https://github.com/CliMA/CloudMicrophysics.jl/pull/320

CC: @charleskawczynski @nefrathenrici @odunbar

**Comment by charleskawczynski** [comment]
Tuples are a better choice if they’re small. If it’s larger than ~100, go with vectors, if it’s less than 20, go with tuples. If it’s somewhere in between, try tuples and see if compilation times are reasonable.

One advantage of using tuples is that they’re GPU-friendly out of the box. If you use vectors, then you’ll need to add a CUDA extension with adapt calls to make your struct work inside CUDA kernels / broadcast expressions. Also, if the length of the tuple/vector is iterated over, the tuple will allow for loop unrolling, which is more likely performant.

**Comment by trontrytel** [comment]
Thanks for the input! Seems like there is no one definitive answer. I'll stick to converting to a tuple inside my constructor.

**Comment by odunbar** [comment]
I would say that performance is not going to be an issue here, as these are in the length <100, and will only be used in the case of retrieval and then immediate build of the struct. as in the example. Once inside the struct they are no longer stored as a vector - except in the case of multidimensional parameters e.g. something that stores neural net weights.
