### ISSUE TITLE
!! Docs are not being updated with new PRs 

### ISSUE THREAD

**Issue by odunbar** [CliMA/CLIMAParameters.jl#176]
the docs link on the home page is very outdated, there seems to be some disconnect in which branch is being updated / which branch the docs are being generated from.

E.g. current PR open has 
https://clima.github.io/CLIMAParameters.jl/previews/PR164/

which are more recent than the link from the homepage
https://clima.github.io/CLIMAParameters.jl/dev/

**Comment by nefrathenrici** [comment]
Deployment broke when we moved from bors to the github merge. We need to run the deployment when `main` is pushed.
