### ISSUE TITLE
Variable name changes

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/CLIMAParameters.jl#99]
This issue is meant to track variable name changes that we'd like to make. Since changing variable names involves releasing a breaking version, which requires propagating through many packages, it makes sense to apply these changes in batches to avoid excessive work.

Here is a list of names we'd like to change:

 - `microph_scaling ` -> `microph_scaling_evap`

cc @trontrytel

**Comment by trontrytel** [comment]
Thank you @charleskawczynski 

I was thinking the same thing. We should collect a bunch of breaking changes to Parameters and weigh in when the number is big enough to warrant the work to propagate the change throughout all the repos

**Comment by odunbar** [comment]
https://docs.google.com/spreadsheets/d/1T3wXWv0tc6O4YuN-7OxMDtezV61RXcUO6DP-eOCXnUc/edit#gid=0

This is something we have already started here. Please add to the list where necessary

**Comment by trontrytel** [comment]
Sorry for replying late! @odunbar why a separate spread sheet and not a github issue? 

Do you have a lot of the breaking changes parameters piled up there? I was hoping to change the above name and to merge https://github.com/CliMA/CLIMAParameters.jl/pull/88 and do a breaking release soon(ish). Do you have anything else that could be merged within a week that would results in a breaking change?

**Comment by odunbar** [comment]
I guess as I've [the link to this sheet elsewhere](https://docs.google.com/spreadsheets/d/1T3wXWv0tc6O4YuN-7OxMDtezV61RXcUO6DP-eOCXnUc/edit#gid=0) the privacy idea is somewhat out the window.

Last year we asked all the groups to contribute their parameters, units, naming conventions, descriptions to a shared sheet. For sharing and editing it was the most convenient format at the time. I do not think it is something we need to keep up-to-date, but should act more as an archive/or starting point for most parameters that are (likely) already in the ClimaParameters list. I expect as every parameter used to be called like `T` or `kappa`, that breaking changes will be frequent as naming conventions change to the more descriptive style.

Nothing should affect your current change.

**Comment by sajjadazimi** [comment]
I replaced microphysics SB2001 scheme by SB2006 which expands SB2001 by more equations. As a result, the parameters of SB2001 are now redundant. I'd like to remove the following list of parameters in the next breaking release:
 - `kc_SB2001`
 - `kr_SB2001`
 - `xstar_SB2001`
 - `ν_SB2001`
 - `A_phi_au_SB2001`
 - `a_phi_au_SB2001`
 - `b_phi_au_SB2001`
 - `τ_0_phi_ac_SB2001`
 - `c_phi_ac_SB2001`

**Comment by szy21** [comment]
I would like to change `entr_tau` to `entr_inv_tau` and `detr_tau` to `detr_inv_tau`

**Comment by trontrytel** [comment]
Thank you!
